# Listeners
listeners.tcp.default = 5672

# Management
management.tcp.port = 15672


# Resource Limits
vm_memory_high_watermark.relative = 0.7

# Default User (Overrides via ENV vars if set, but good here for reference)

# Import Definitions (Queues, Exchanges, Bindings)
management.load_definitions = /etc/rabbitmq/definitions.json

