# Sink Configuration (RabbitMQ)
debezium.sink.type=rabbitmq
# RABBITMQ CONFIGURATION (Point this to Server B Public IP/DNS)
debezium.sink.rabbitmq.connection.host=rabbitmq
# In production, replace 'rabbitmq' above with the actual IP address (e.g., 203.0.113.10)
debezium.sink.rabbitmq.connection.port=5672
debezium.sink.rabbitmq.connection.username=user
debezium.sink.rabbitmq.connection.password=password
# Exchange Name (Must match definitions.json)
debezium.sink.rabbitmq.exchange=lis
debezium.sink.rabbitmq.routingKey=debezium

# Source Configuration (MySQL)
debezium.source.connector.class=io.debezium.connector.mysql.MySqlConnector
debezium.source.offset.storage.file.filename=/debezium/data/offsets.dat
debezium.source.offset.flush.interval.ms=60000

debezium.source.database.hostname=

debezium.source.database.port=
debezium.source.database.user=
debezium.source.database.password=
debezium.source.database.server.id=
debezium.source.snapshot.fetch.size=1000
debezium.source.database.server.name=lis-tarqeem-connector
debezium.source.topic.prefix=lis
debezium.source.database.include.list=

debezium.source.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.source.schema.history.internal.file.filename=/debezium/data/schema_history.dat

# Heartbeat Configuration
debezium.source.heartbeat.interval.ms=30000

# Format (JSON)
debezium.format.key=json
debezium.format.value=json
debezium.source.decimal.handling.mode=double
